### ISSUE TITLE
Consider the MUST requirement for gatewayclass finalizer

### ISSUE THREAD

**Issue by mlavacca** [kubernetes-sigs/gateway-api#1411]
**What would you like to be added**:

The `GatewayClass` [doc](https://github.com/kubernetes-sigs/gateway-api/blob/2738bba07d9cc98f4f0334a638c26d2159ae12b0/apis/v1beta1/gatewayclass_types.go#L45-L50) states that 
```
// Whenever one or more Gateways are using a GatewayClass, implementations MUST
// add the `gateway-exists-finalizer.gateway.networking.k8s.io` finalizer on the
// associated GatewayClass. This ensures that a GatewayClass associated with a
// Gateway is not deleted while in use.
```

Since this is described as a MUST in the API, it should be checked by a conformance test that creates a `GatewayClass` and a `Gateway` that uses it. Once the `Gateway` is created, the existence of such a finalizer should be checked on the `GatewayClass`.

**Why this is needed**:

This is needed because the existence of such a finalizer is stated as mandatory.

**Comment by howardjohn** [comment]
Can we consider changing the spec here? This is a bad idea IMO

**Comment by mflendrich** [comment]
xref https://github.com/Kong/gateway-operator/issues/432

**Comment by youngnick** [comment]
Just found this in my notifications, sorry for the delay.

@howardjohn could you explain more about why you think this is a bad idea? Currently, the GatewayClass is a required resource, so without a GatewayClass, Gateways must not be processed. So, removing the GatewayClass should also remove associated Gateways.

**Comment by howardjohn** [comment]
I don't think finalizers are a good design in general; there are very rare cases they are useful but normally they just lead to frustration (see https://stackoverflow.com/questions/52369247/namespace-stuck-as-terminating-how-i-removed-it, one of the most upvoted questions for `kubernetes`). Its maybe a _bit_ better in this case since its not a namespace scoped resource

**Comment by shaneutt** [comment]
We must resolve this before GA, but it may be better to make this a `SHOULD` instead of a `MUST` as the way to resolve this, as saying that an implementation _must_ implement a finalizer is not great. We would appreciate having a contributor help make the final decision and then make the update.

/help
