### ISSUE TITLE
Gateway priority field for conflict resolving

### ISSUE THREAD

**Issue by ivanmatmati** [kubernetes-sigs/gateway-api#1486]
**What would you like to be added**:
A priority field in Gateway. It should be an integer setting the priority of this Gateway over the others in case of conflict at Listener level. A variant of this idea would be to set this field directly at Listener level.
**Why this is needed**:
Some implementation of GW Api won't spin resources on the fly according the different gateways but rather use a single dataplane to gather them all in a single place. Then arises an issue when two different gateways have the same ports for TCP routing. We have the rule that prevents that a list of listeners in the same gateway could go wrong in this regard but not if we consider a list of gateways where same ports can appear multiple times considering their different list of Listeners. A conversation with @youngnick in gateway slack channel ended up with the idea that the same algorithm from AllowedRoutes should be applied. But with TCP this algorithm boils down to creation timestamp and alphabetical order which is rather static. Suppose you want to put a new gateway at first place, you must then recreate all the gateways because of timestamp order. It doesn't sound very practical and it's because the order is based on resources rather than on configuration and explicit intention.

**Comment by youngnick** [comment]
Thanks for logging this issue @ivanmatmati!

I think that this is pretty interesting to discuss, I don't know of any other Kubernetes resources that have a mechanism like it. (not saying there aren't any, just that I haven't seen them).

Seems like you'd want an optional, top-level integer field that would only be used in the event of a conflict? If we did that, it would need _very_ clear explanation that it's _only for conflict resolution_, not a general ordering priority.

Remember that, for a conflict resolution mechanism to work for Kubernetes objects, it can't use anything other than things that are _part of the object when it's retrieved from the API_. There's no way to say "just use the most recent one" that doesn't also mean that new incorrect config will break everything - that's why we chose "oldest one wins".

Interested to hear if anyone else has thoughts or prior art here.

**Comment by howardjohn** [comment]
The fallback timestamp rule isn't really intended as long term conflict resolution, but rather that we have to pick *something* and that is a stable way to do so. If you are in this state though, you ought to fix your conflicts at a higher level. Do you intend to have conflicting ports long term? If so, why?
