### ISSUE TITLE
Conformance RoundTripper should allow for custom http.RoundTripper implementation

### ISSUE THREAD

**Issue by briantkennedy** [kubernetes-sigs/gateway-api#1496]
**What would you like to be added**:

Allow for optionally constructing the `roundtripper.DefaultRoundTripper` with a custom `http.RoundTripper`.

**Why this is needed**:

Users may need to run conformance tests through a SSH tunnel or Proxy where a custom `http.RoundTripper` is required to connect to the load balancer.

https://github.com/kubernetes-sigs/gateway-api/blob/0adb8a8bd14672db6ea16ab6191a828295fe8d04/conformance/utils/roundtripper/roundtripper.go#L70

**Comment by LiorLieberman** [comment]
curios if there is any progress with it?

**Comment by akash-gautam** [comment]
@LiorLieberman Not yet, this one slipped out of my radar unfortunately. Will start on this soon.

**Comment by ashutosh887** [comment]
@akash-gautam Should I give it a try now?
Please assign me @LiorLieberman

**Comment by robscott** [comment]
Hey @ashutosh887, I think you're welcome to take this one on unless @akash-gautam is actively working on this. Thanks for volunteering!

**Comment by ashutosh887** [comment]
Thanks @robscott 
I'll get started with it
Please guide me a bit what is needed to be fixed

**Comment by shaneutt** [comment]
Just keep in mind @ashutosh887 that you've assigned multiple issues to yourself within a short period of time: it's often best to take one or two and focus in on those according to priority (priority labels, plus milestones). If you want to focus in more on #1515 or #1639 it would be OK to leave this one unassigned for now and come back to it OR open it up for other contributors to grab in the meantime (as this one is considered more of a long-term maintenance gain than a milestone deliverable).

As for your question: this issue is requesting that a `RoundTripper` option be made available in https://github.com/kubernetes-sigs/gateway-api/blob/0adb8a8bd14672db6ea16ab6191a828295fe8d04/conformance/utils/roundtripper/roundtripper.go#L70 to override the defaults, which would enable running the test suite when a SSH tunnel or proxy is in place. If you do not have an implementation to test changes to this on, OR more specifically an implementation that would need to utilize an SSH tunnel or proxy, it may be better to leave this one for someone with an implementation with that need who can actively test it.

**Comment by ashutosh887** [comment]
Thanks @shaneutt 
Sure Sir... I respect your suggestions.

**Comment by akash-gautam** [comment]
Starting work on this one today. 
/assign

**Comment by akash-gautam** [comment]
This issue can be closed as per the discussions [here](https://github.com/kubernetes-sigs/gateway-api/pull/1882)

**Comment by robscott** [comment]
Thanks @akash-gautam, sorry for the mixup!
