### ISSUE TITLE
Improving documentation for handling multiple hostnames on TLSRoutes

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/gateway-api#1583]
**What would you like to be added**:

Improvements to the guidance on TLSRoutes relevant to multiple hostnames, providing insights on how implementations should handle this.

**Why this is needed**:

Multiple implementers brought this up in the [Dec 9th 2022](https://docs.google.com/document/d/1eg-YjOHaQ7UD28htdNxBR3zufebozXKyI28cl2E11tU) community meeting as a documentation pain point.

**Comment by youngnick** [comment]
I think the thing that is the most unclear is "what happens when there are multiple hostnames in a TLSRoute?".

My rough thoughts were:
- the spec should not mandate that implementations have to unwrap certificates and check that a name in the certificate matches a hostname in the TLSRoute (indeed, this isn't possible in forwarding cases).
- Because of that, the hostnames should be a "request must match at least one of these hostnames"
- The usual hostname match rules between the Listener hostname and the Route hostname should apply for each hostname in the TLSRoute hostnames section.

That's my thoughts, but interested to hear if anyone else has any here.
