### ISSUE TITLE
Conformance test to exercise adding multiple listeners

### ISSUE THREAD

**Issue by dprotaso** [kubernetes-sigs/gateway-api#1607]
From: https://github.com/kubernetes-sigs/gateway-api/pull/1586#discussion_r1050061001_

It sounds like there's a gap in the conformance suite as we it doesn't exercise adding new listeners to a gateway.

The language in the spec seems to indicate you should be able to update Gateways and add/remove listeners.

**Comment by sunjayBhatia** [comment]
Should capture the expectation that listeners with different ports, hostnames, protocols, etc. will be tested

**Comment by nilabjasarkar123** [comment]
Yes, it is possible to update a Kubernetes Gateway resource and add or remove listeners. A Gateway resource in Kubernetes is used to configure a load balancer for a group of Services, and a listener specifies a port and protocol that the load balancer should listen on.

To add or remove a listener from a Gateway resource, you can simply update the spec.servers field in the resource definition. The spec.servers field is a list of Server objects, and each Server object represents a listener on the load balancer.

Here is an example of how you can add a listener to a Gateway resource using the kubectl command-line tool:

Copy code
kubectl patch gateway my-gateway --type='json' -p='[{"op": "add", "path": "/spec/servers/0", "value":{"port":{"number":8080,"name":"http","protocol":"HTTP"},"hosts":["example.com"]}}]'
This will add a listener to the Gateway resource my-gateway that listens on port 8080 for HTTP traffic, and directs traffic to the hosts "example.com".

To remove a listener from a Gateway resource, you can use a similar kubectl patch command, but with the op field set to "remove" instead of "add".

It's worth noting that in order for these changes to take effect, you will need to have an Ingress controller running in your cluster. The Ingress controller is responsible for fulfilling Gateway resources and configuring the load balancer accordingly.

I hope this helps! Let me know if you have any more questions.



---------------------------------------------------------------------------------------------------
used chatGPT to found the solution it give me this

**Comment by robscott** [comment]
Hey @nilabjasarkar123, your comment does not add to the discussion here. This issue is intended to track adding a conformance test for a specific topic, your ChatGPT generated response is attempting to answer a question that was not asked.

**Comment by dprotaso** [comment]
FYI - the merge test only assumes port 80 & 443 can be added/removed

There's a follow up issue here - https://github.com/kubernetes-sigs/gateway-api/issues/1842
