### ISSUE TITLE
AttachedRoutes spec does not clarify how to handle partially invalid states

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#1626]
**What happened**:
The current AttachedRoutes spec is rather vague and does not clarify how partially invalid states should be handled.
https://github.com/kubernetes-sigs/gateway-api/blob/46d40889ea70291da0614274931c2ffacdc0b612/apis/v1beta1/gateway_types.go#L671-L673 

This came up in https://github.com/kubernetes-sigs/gateway-api/pull/1624#discussion_r1059174997.

**What you expected to happen**:
I expected clear guidance on how to set this value for partially invalid listeners or routes.

**Comment by robscott** [comment]
Here are a couple possible options:

**1. AttachedRoutes should only represent Routes that have actually been programmed with the Gateway** 
In general, I think this would mean that the Listener would have to have reached the "Programmed" state and Routes would have had to reach the "Accepted" state. Importantly, if a Listener or a Route transitioned to an invalid state in the future but was still programmed in the underlying dataplane, it would be considered "Attached". 

**2. AttachedRoutes should not care about the status of the Listener or Routes**
If a Route is attempting to attach to a Listener and the Listener allows for that connection, it should be counted towards AttachedRoutes. This would not take into consideration the status of either Listener or Route. For example, even if a Route referred to a non-existent Service or a Listener referred to a non-existent TLS cert, AttachedRoutes would still represent the number of connected resources.

At first glance, 1 seems like it would be best for users but hardest to implement, and 2 seems like it would be simplest to implement. Also open to any other alternative approaches.

**Comment by mikemorris** [comment]
In response to conversation during the Gateway API weekly meeting, I don't think renaming or deprecating `attachedRoutes` would actually make sense semantically - "acceptance" is mostly a property in relation to the Gateway API controller, "attached" (to the extent that the docs still use that language) has become more a property in relation to a Gateway listener/dataplane and correlated with a "programmed" status if applicable (@shaneutt described this similarly) - it makes sense how this evolved historically, but I think they're two separate concepts now.

+1 to definition 1️⃣ , if there's a need to express a count of routes targeting a Gateway listener, we could possibly introduce a new field `targetedRoutes` or `acceptedRoutes` (I can't think of a better term that signifies the listener is _being targeted by the routes_ rather than the listener targeting the routes without implying a child relationship which wouldn't be accurate, open to suggestions).

It would be important to define edge cases like if a route not permitted by [`AllowedRoutes`](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io%2fv1beta1.AllowedRoutes) or route type not present in the [`supportedKinds`](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io%2fv1beta1.ListenerStatus) field should be included in an `acceptedRoutes` total - I think those would both be excluded if we restrict this count to only `Accepted` routes.

I'm unsure if/how these fields should be set if the listener itself is in an `Accepted: false` state for some reason (TLS certificate invalid, port unavailable, etc).

For operators, comparing these two counts might be a helpful first triage step - "are there some `Accepted` routes targeting this listener that are not successfully attached?"

**Comment by shaneutt** [comment]
Here is a proposed plan of attack, going with number 2 above ("AttachedRoutes should not care about the status of the Listener or Routes"):


1. add an official definition of "attached" in this context, with a meaning aligning with not caring about listener or route status
2. add documentation which explains what it means above
3. create an issue to create conformance tests which check that programmed AND non-programmed routes get counted
4. kick up an issue to add a `ProgrammedRoutes` later if the community finds that useful

**Comment by shaneutt** [comment]
Talked to @sunjayBhatia about this, and he's up for taking this one on.

/assign @sunjayBhatia 

We expect resolving this nearly "autoresolves" #1925 as well.

Thanks @sunjayBhatia! Let us know if you run into any blockers.

**Comment by shaneutt** [comment]
@sunjayBhatia just checking in, any trouble moving this one (and #1925 ) forward? Let us know if we can help!

**Comment by sunjayBhatia** [comment]
Submitted https://github.com/kubernetes-sigs/gateway-api/pull/2396

**Comment by sunjayBhatia** [comment]
Also add https://github.com/kubernetes-sigs/gateway-api/issues/2402
