### ISSUE TITLE
GAMMA: Consider a "from" and "to" in route references

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#1640]
https://github.com/kubernetes-sigs/gateway-api/pull/1493#discussion_r1018372989 had a lot of discussion about possible extensions to the matching API. However, they were out of scope on the PR for now, so moving to an issue

**Comment by mateiidavid** [comment]
Thanks for opening this! I brought this up in the GAMMA meeting that happened on the 17th. John said this might be an optional thing since not all meshes may be able to implement these extensions in the matching API. I wanted to re-iterate on (and document) what our needs are, and what we'd like to see. Most of this is copy & pasted from the original thread. 

In #1493 we changed the spec to allow for a hierarchy in routes. Routes defined in a consumer namespace that attach to a `Service` will take precedence over routes attached to the same `Service` that exist in the _producer namespace_. For the majority of cases, this is fine. This does imply that the route, and any policies that apply to that route (or the targeted `Service`) will apply for _all_ workloads in the consumer namespace.

On the Linkerd side, we'd like to have a bit more flexibility and limit the behaviour to only a subset of pods. There might be situations in which our users will need to enforce different policies for consumers in the same namespace. We were thinking this could be addressed with a resource that captures the Consumer-to-Service binding relationship. Something between ServiceBinding and ServiceProjection (although projection probably fits better as a model and name). For example:

```
spec:
  consumerRefs:
    - group: apps
      kind: Deployment
      name: web
  providerRef:
    kind: Service
    namespace: backend
    name: emoji
status:
  conditions: ...
```

The resource describes traffic originating from a consumer workload (deploy/web) to a producer service (service/emoji). The status is added in for conflict resolution.

This is similar to @michaelbeaumont's idea, at least conceptually. In the write-up, it was mentioned that

> In the mesh case, it's important to be able to talk about the source of a request when doing traffic routing. That's what the idea of consumer/producer routes in this PR expresses. A consumer route is "only requests from this namespace" and a producer route is "requests from anywhere in the mesh".
>
> The PR gives the Namespace of an HTTPRoute the ability to scope a route based on source of a request. But doing this also answers the question of who can attach to a Service as a consumer/producer.

The post goes on further to say:

> Is there a way to answer these two questions less implicitly/separately?

And suggests a `to and from` tuple in the `parentRef`. I believe this would also work for our use case. Regardless of how this is solved, think it's important to at least discuss it in a more official setting. 

@kflynn not sure if you have anything additional to say. Corrections are more than welcome. Thanks in advance!

**Comment by mikemorris** [comment]
Continuing discussion from the original thread:
>     SHOULD allow control by the cluster operator (mesh administrator) to grant permission for whether HTTPRoute resources in a given namespace are allowed to configure mesh traffic routing.
> This doesn't feel covered yet, right?

My interpretation of this was that this would be achieved by either Kubernetes RBAC (users not being given permission to create `HTTPRoute` resources) or namespace "enrollment" of some sort (allow/deny list of namespaces in something like a cluster-scoped `Mesh` CRD) - I was _not_ expecting that cluster admins would likely to be authoring `HTTPRoute` resources.

---

Following from this, I think limiting the `to` targeting for _producer_ routes and `from` targeting for _consumer_ routes to same-namespace is relatively important for keeping configuration local/discoverable and reducing surprises (config from an arbitrary third namespace should likely _not_ be modifying requests unexpectedly), but agree that making these roles more explicit could be potentially improve the UX.

Limiting the scope of consumer routes to only requests coming from a specified workload _does_ feel like a use case we should aim to support, and I think this narrower scope somewhat overlaps with use cases that would benefit from a layered (`consumer then producer` instead of `consumer or producer`) application as described in https://github.com/kubernetes-sigs/gateway-api/pull/1493/files#r1034985599

Limited-scope producer routes feel less useful, but I'd be curious to hear any specific use cases. Limited-scope producer _policy_, such as further constraining timeouts or retries from a specific consumer does feel important for isolating abusive consumers, but that's a bit different scope from routing I think.
