### ISSUE TITLE
Optional Listeners in both Gateway.Spec and Gateway.Status

### ISSUE THREAD

**Issue by maplain** [kubernetes-sigs/gateway-api#174]
**What would you like to be added**:
Optional Listeners in both Gateway.Spec and Gateway.Status

**Why is this needed**:
At the moment, the fields Gateway.Spec.Listeners and Gateway.Status.Listeners are not optional and must be non-empty. These requirements do not support the following use cases:

- The Gateway has no Listeners because the Gateway resource’s route selector points directly to a Service resource

- The Gateway has status conditions unrelated to Listeners

The proposal is to allow Gateway.Spec.Listeners and Gateway.Status.Listeners to both be “optional, omitempty” in order to satisfy the above use cases.

**Comment by robscott** [comment]
Hey @maplain, thanks for filing this issue! I'm not sure we'd ever planned for directly linking Gateways to Services, but I think it may have been discussed as part of the broader L4 conversation. It would be helpful to understand your use case a bit better. If a Gateway has no listeners and is only used to point to a Service, what value does it provide? I think @JeremyOT volunteered to work on a potential spec for TCPRoute, so he might have some more thoughts on this as well.

**Comment by maplain** [comment]
@robscott This is not limited to our specific use case. 

It's also preventing the creation of a Gateway programmatically without specifying an empty Status.Listeners and Status.Conditions, which is unnecessary and clutters the code.

For example, creating a Gateway without Status.Listeners and Status.Conditions in a unit test will cause the following error.
```
			Spec: svcapiv1alpha1.GatewaySpec{
				Class: "haproxy-lb",
				Listeners: []svcapiv1alpha1.Listener{
					{
						Name: "placeholder",
					},
				},
				Routes: svcapiv1alpha1.RouteBindingSelector{
					RouteSelector: &metav1.LabelSelector{
						MatchLabels: map[string]string{
							lbapiv1alpha1.ServiceRouteTypeLabelName:        lbapiv1alpha1.ServiceRouteTypeDirect,
							lbapiv1alpha1.ServiceRouteGatewayNameLabelName: "httpd",
						},
					},
				},
			},

```

```
                            Status: "Failure",
                            Message: "Gateway.networking.x-k8s.io \"httpd\" is invalid: [status.conditions: Invalid value: \"null\": status.conditions in body must be of type array: \"null\", status.listeners: Invalid value: \"null\": status.listeners in body must be of type array: \"null\"]",
                            Reason: "Invalid",
                            Details: {
                                Name: "httpd",
                                Group: "networking.x-k8s.io",
                                Kind: "Gateway",
                                UID: "",
                                Causes: [
                                    {
                                        Type: "FieldValueInvalid",
                                        Message: "Invalid value: \"null\": status.conditions in body must be of type array: \"null\"",
                                        Field: "status.conditions",
                                    },
                                    {
                                        Type: "FieldValueInvalid",
                                        Message: "Invalid value: \"null\": status.listeners in body must be of type array: \"null\"",
                                        Field: "status.listeners",
                                    },
                                ],
```

**Comment by akutz** [comment]
Hi @JeremyOT,

I'd love to chat! We're also working on a spec for TCPRoute, and I've asked @nikhita to take point on engaging this project for potential synergistic opportunities now and in the future between our projects. Perhaps we can sit down and see where we might be able to help one another? 

FWIW, I previously defined a `TcpRoute` in #132, but I closed the issue at the time because it basically required TLS to use SNI for routing. I've had a subsequent idea to use the ports for routing since I now understand the GW is the VirtualServer, not the LB. 

Anyway, would love to sync up sometime!

**Comment by akutz** [comment]
Hi @robscott,

> I'm not sure we'd ever planned for directly linking Gateways to Services, 

We did not plan to do so either, but it just sort of worked out this way. The reason being is because we did not want to jump the gun on `TcpRoute` or make any commitments to types we may want to remove in the future. The fact is, the `Service` and `Endpoints` resources contain all of the information needed for L4 routes:

* Frontend port(s)
* Backend port(s)
* Backend address(es)

We are actively working to upstream the project we're developing called the _Load Balancer API_. It defines a concept we refer to as _service routes_. Here is a snippet of that to help explain the background here:

## Service Routes

The load balancer API supports a concept built on top of the Service APIs known as _service routes_. A service route allows a `Service` to be selected via the `Gateway` resource field `spec.routes`. For example, the following `Gateway` resource uses the field to select a `Service` resource as a direct route:

```yaml
apiVersion: networking.x-k8s.io/v1alpha1
kind: Gateway
metadata:
  name: echo
  namespace: echo-system
spec:
  class: haproxy-lb
  routes:
    routeSelector:
      matchLabels:
        service.route.lbapi.run.tanzu.vmware.com/type: direct
        service.route.lbapi.run.tanzu.vmware.com/gateway-name: echo
        service.route.lbapi.run.tanzu.vmware.com/gateway-namespace: echo-system
```

The rest of this section discusses the two types of service routes and the labels and annotations used to connect a `Service` to a `Gateway`.

### Service Route Types

There are two types of service routes: _direct_ and _indirect_.

#### Direct Service Route

A direct service route means:

* the service ports are treated as the ports for the frontend
* the endpoint ports are treated as the ports for the backend
* the IP addresses from the `Service` resource’s associated `Endpoints` resource is used as the addresses for the backend servers

The Project Pacific implementation of the load balancer API uses direct service routes.

#### Indirect Service Route

An indirect service route means:

* the service ports are treated as the ports for the frontend
* the node ports are treated as the ports for the backend
* the node addresses must be collected from each `Node` resource with a ready condition
 
This implementation of a service route would be used when the load balancer controller is running on the same host as the immediate `Service` resource.

### Service Labels

Setting the following label(s) on the Service:

* `service.route.lbapi.run.tanzu.vmware.com/gateway-name`
    The name of the `Gateway` resource for which the `Service` is a route

* `service.route.lbapi.run.tanzu.vmware.com/gateway-namespace`
    The optional namespace of the `Gateway` resource

*	`service.route.lbapi.run.tanzu.vmware.com/type`
    The type of service route: `direct` or `indirect`

### Service Annotations

It is possible to set annotations on `Service` resources to configure the backend infrastructure using the following pattern:

* `lbapi.run.tanzu.vmware.com/PROPERTY`

This section includes some of the properties that are common to most load balancer platforms and should be implemented by a controller for the Load Balancer API.

* Load Balancer Name
    `lbapi.run.tanzu.vmware.com/load-balancer-name`
    This annotation specifies the name of the load balancer resource that this Service should belong to. An error should be included in the `Gateway` resource's status field if a `GatewayClass` (referencing the load balancer) with the specified name does not exist.

* Virtual Server Algorithm
    `lbapi.run.tanzu.vmware.com/algorithm`
    This annotation specifies the load balancing algorithm that should be used for a given `Service`. Common load balancing algorithms that should be supported by most platforms include round robin, least connections and source/destination hashing. Invalid algorithms should be included in the status field of the `Gateway` resources.

* Virtual Server IP
    `lbapi.run.tanzu.vmware.com/ip-address`
    This annotation specifies the desired IP address to use for the virtual server created on the load balancer. If not specified, controllers watching the API should automatically allocate an available virtual server address. If a user specifies an already allocated virtual server IP, the error should be reported in the status field of the `Gateway` resource.

### Additional Properties

It is also possible to supply configuration properties for specific platforms using the following pattern:

* `PLATFORM.platform.lbapi.run.tanzu.vmware.com/PROPERTY`

For example, the list below illustrates how to use the above pattern to specify platform-specific properties for several, well-known load balancer providers:

* `nsxt.platform.lbapi.run.tanzu.vmware.com/an-nsxt-property`
*	`avi.platform.lbapi.run.tanzu.vmware.com/an-avi-property`
*	`haproxy.platform.lbapi.run.tanzu.vmware.com/an-haproxy-property`

**Comment by akutz** [comment]
Hi @JeremyOT,

FWIW, I loosely defined a TCPRoute along these requirements:

* Similar to HTTPRoute
* Supports Listener matching by TLS+SNI
* Supports Listener matching by target port
* Defines a target port (intOrStr)
* Forwards to a resource that contains endpoint information, (ex. v1/Endpoints)

**Comment by robscott** [comment]
Hey @maplain and @akutz, thanks for the detailed explanations! I think you're completely right that `Listeners` and `Conditions` should be optional in status, spec seems a bit more complicated to me though. 

I think what we decide for `spec.Listeners` will have to be closely tied to our approach for L4. I can't think of a great use case for making this optional outside of L4, but definitely do see the significant overlap between a Service spec and any potential intermediate TCPRoute. I haven't spent enough time thinking about what that should look like, but I'm interested to see any ideas you and/or @JeremyOT come up with around this.

**Comment by akutz** [comment]
> I can't think of a great use case for making this optional outside of L4

So why is that not enough? It helps L4 by enabling tying a Service directly to a Gateway and does not hurt L7.

FWIW, the case for Service routes (which is totally and completely enabled by the current spec since there is no qualifier on what is selected via a route selector) is that no one has to reconcile the ports from Service resources into Listeners or future, possible TCPRoute resources.

**Comment by robscott** [comment]
Sorry, that was not my intention. I was trying to say that determining how we link Gateways to Services for L4 protocols is a prerequisite to making `spec.Listeners` optional. If we had a plan for L4 formalized that included linking directly to Services, this could make a lot of sense, but I don't believe we do yet. I was certainly not meaning to imply that L4 was in any way less important than L7, simply that it was not as well defined right now. We already have a pattern for how L7 protocols link to Services with HTTPRoute, we don't have the same clarity with L4 yet.

**Comment by JeremyOT** [comment]
> FWIW, I loosely defined a TCPRoute along these requirements:
> 
> * Similar to HTTPRoute
> * Supports Listener matching by TLS+SNI
> * Supports Listener matching by target port
> * Defines a target port (intOrStr)
> * Forwards to a resource that contains endpoint information, (ex. v1/Endpoints)

Hi @akutz - I've been thinking along the same lines. It would be great to chat, and maybe walk through some example scenarios. Let's coordinate on K8s slack.

**Comment by akutz** [comment]
Sgtm @JeremyOT , thank you. It will be great to finally chat with you since we kept crossing paths in the multi cluster space. My team was refocused shortly after you and I engaged there, and so I’m glad we’ll finally have a chance to work on something together.

**Comment by jpeach** [comment]
/remove-lifecycle rotten

This issue needs to be re-triaged as the API has changed substantially.

**Comment by robscott** [comment]
@maplain and @akutz - I've created a related proposal/issue here: https://github.com/kubernetes-sigs/service-apis/issues/529. I think that approach could potentially address the goals of this issue, would appreciate your feedback.
