### ISSUE TITLE
How to enable gzip through the definition of gateway

### ISSUE THREAD

**Issue by lllwan** [kubernetes-sigs/gateway-api#1799]
All controllers have the ability to enable gzip. My question is how to enable gzip through the definition of gateway.

**Comment by youngnick** [comment]
Thanks for this issue @lllwan, so you'd like a standard field to control whether flows are automatically gzipped?

I'll be honest, I thought that config like this would largely be a configuration at the implementation level.

I'd love to see some use cases demonstrating needing to configure things at the Gateway level (that is, walking me through how people need this customized on a per-Gateway basis).

**Comment by lllwan** [comment]
I think we should provide a standard field or any other way to enable gzip in HTTPRoute, because when I cannot enable it through the declaration of gateway, I will need to start to care about whether the infrastructure uses isio or nginx, and use the corresponding heterogeneous way to achieve the goal.

**Comment by youngnick** [comment]
I'll be honest, I assumed that most implementations would just enable gzip, and have a way to _disable_ it if you wish, rather than the other way around. That's what we did for Contour, and I _think_ for Envoy Gateway as well, and you can disable this automatic Gzip encoding when configuring the implementation. 

I'm worried about adding very specific features like encodings to the larger object, if we do Gzip, why not other settings? How big will the Gateway need to be once we have all of those settings?

Maybe some other implementors could comment here:
- What does your implementation do for Gzip configuration?
- Do you think it would be useful for there to be Gateway-level configuration of this setting?
- What criteria should we be using to decide if these settings should be added?

**Comment by arkodg** [comment]
we haven't gotten a request for this in Envoy Gateway yet, but it looks like a common use case 
* Istio doesnt have an API field yet, users are using EnvoyFilter to configure this https://github.com/istio/istio/issues/18443
* Looks like Contour enables it by default, and provides a way to opt out which some users want https://github.com/projectcontour/contour/issues/3024

Probably needs more use cases to figure out whether this should be opt in or opt out feature

Steering clear of the _HOW_ for now

**Comment by brianehlert** [comment]
From an NGINX perspective it is an option, but the question comes; where?
Do you want it for the entire Gateway and all the hostnames / paths that it serves (listener)?  
Or do you want to granularly enable it for specific xRoutes? 
Or even individual paths?
That is simply on | off without discussing knobs.

And I am also going to lend that NGINX doesn't enable it by default.  Which has both positive and negative.

**Comment by shaneutt** [comment]
We discussed this on the community call today and one important piece of feedback is that there's a desire to approach this problem in a more generic way, so that we're not entirely focused on gzip but rather how to apply configuration like that more broadly.

It seems in general there's not really much clarity on _how_ we would implement this yet and we should likely have at least a small [GEP](https://gateway-api.sigs.k8s.io/geps/overview/) for this:

/kind gep

We would also need someone who feels strongly about this to champion this issue and drive it forward, @lllwan are you interested in getting a GEP started for this?

**Comment by shaneutt** [comment]
We would like to see a community member who's interested push this forward with a GEP, but we don't see this one as being something that needs to block GA so we'll hold on this until after `v1.0.0`.

/priority backlog
