### ISSUE TITLE
Goals (or boundary) of the Gateway API project

### ISSUE THREAD

**Issue by arkodg** [kubernetes-sigs/gateway-api#1815]
**What would you like to be added**:
A high level document highlighting goals of the project

**Why this is needed**:
With the announcement that Gateway API is planning on graduating to [GA](https://github.com/kubernetes-sigs/gateway-api/discussions/1801) soon, (which is great news !), a high level document highlighting goals of the project would help
* potential end users who are considering to migrate their intent from existing APIs to Gateway APIs
* implementation projects can better plan what features may be supported natively in the future using the Gateway API and which features need to be supported using Extension APIs. 

For e.g. lets take the OIDC based Authentication feature, this is a common ask from users ([slack ref](https://kubernetes.slack.com/archives/CR0H13KGA/p1678343318405499)), hoping the goals doc helps reveal whether
* This feature API can be supported natively ( I understand actual support is dependent on multiple factors such as community contributions )
* The feature API will never be supported natively

**Comment by youngnick** [comment]
Sorry for the delay on this one @arkodg.

I think it's difficult to make a call about which features will be supported natively, because we've designed the conformance levels to imply a possible flow for features (namely, ImplementationSpecific -> Extended -> Core ).

The idea is that, to help us all move faster, people can experiment with ImplementationSpecific things, then if we find something ImplementationSpecific is in wide use, we can bring it into Extended (which will include making it part of native support).

I don't think that any feature work done using one of the standard extension points will be wasted, and I'd be pretty reluctant to say "never" for _any_ feature.

That said, I think that for OIDC auth, it seems _likely_ that it will both widely desired and widely supportable, so it seems reasonable that it would end up in Extended eventually (assuming we can agree on the design).

The reason for this is that, over the years we've been doing this, we've found that it's very easy to spend a _lot_ of time arguing about design in the absence of data from trying to implement some feature, and that encouraging people to prototype something first helps cut the solution space down much more quickly.

At the end of the day, the overall goal of the project is to support _as many_ features as we can make Portable, Extensible, and Role-Oriented. So unless something is _very_ ImplementationSpecific, I think it's unlikely it will Never be supported, it will just need development time.

We have been (and still are) focussing on trying to get the core parts of the API right first (including both API contructs like Gateway and GatewwayClass etc), and getting processes like conformance set up and running. I think that once we start graduating resources to GA and finish with this more basic work, we will be able to increase the velocity of delivering extra, highly-useful features like authentication, rate-limiting, and so on.

**Comment by arkodg** [comment]
thanks for commenting @youngnick, this is very helpful and should help end users as well as implementors better understand what Gateway API can eventually support.

would be great to convert above comment in a goals/scope section for the website. I'm happy to help out with that ( I'll try to  paraphrase above comment )

**Comment by youngnick** [comment]
Yes, I agree that would be great @arkodg! If you want to do that, sounds awesome. I think our initial landing pages need an update anyway.
