### ISSUE TITLE
Add conformance tests for GatewayConditionReady

### ISSUE THREAD

**Issue by arkodg** [kubernetes-sigs/gateway-api#1833]
**What would you like to be added**:
Add an extended conformance test to ensure that when the Gateway `Ready` Condition is set to `True`, all traffic sent through this listener must succeed. [Here](https://github.com/kubernetes-sigs/gateway-api/blob/1c4ae619312754c52e1ff130439caed87132dc54/apis/v1beta1/gateway_types.go#L609-L611) is the condition in the spec.

Relates to https://github.com/kubernetes-sigs/gateway-api/issues/1832#issuecomment-1472858190

**Why this is needed**:
End users can better understand guarantees provided by implementations.

**Comment by gauravkghildiyal** [comment]
I'd like to work on this. 

I'm sorry if I'm missing something obvious and it would be great if someone can help with the following doubt:

So I'm guessing that the `GatewayConditionReady` could be set to true even before any corresponding `Route` resources are programmed into the gateway. If that is the case, is there a way to verify the invariant _"all traffic sent through this listener must succeed."_ without being explicitly aware of the implementation of the listener/gateway? Is there a consensus that when `GatewayConditionReady=False|Unknown`, we would get a connection timeout/refused (or other equivalent) but when `GatewayConditionReady=True`, the TCP connection would succeed (but could return some other application layer error)

**Comment by howardjohn** [comment]
> I'd like to work on this.
> 
> I'm sorry if I'm missing something obvious and it would be great if someone can help with the following doubt:
> 
> So I'm guessing that the `GatewayConditionReady` could be set to true even before any corresponding `Route` resources are programmed into the gateway. If that is the case, is there a way to verify the invariant _"all traffic sent through this listener must succeed."_ without being explicitly aware of the implementation of the listener/gateway? Is there a consensus that when `GatewayConditionReady=False|Unknown`, we would get a connection timeout/refused (or other equivalent) but when `GatewayConditionReady=True`, the TCP connection would succeed (but could return some other application layer error)

That is an excellent point. Ready=False does not imply traffic must fail IMO, just that we aren't 100% certain it will succeed.

However the interaction with route is troubling I think. It can't mean "all routes are ready", IMO, because we wouldn't have anyway to know if it's an outdated condition. Normally we use observedGeneration but this is cross-resource

**Comment by arkodg** [comment]
maybe a `Ready` condition is needed at the route level https://github.com/kubernetes-sigs/gateway-api/blob/20be22d3a2976374772170a6a55a9c8228d1e8c8/apis/v1beta1/shared_types.go#L198 so a user can ascertain that a route is ready to serve traffic ?

**Comment by youngnick** [comment]
A `Ready` condition at Route level would be great, I agree, but I think that in practice, that will be _very_ hard to build. It will mean that every bit of config from every HTTPRoute will need to be tracked in the data plane, so that an implementation can _confirm_ that a _particular_ piece of config that corresponds to _that_ HTTPRoute has been propagated down to the data plane and is ready to pass traffic.

For Envoy data planes, for example, the controller will need to track which filter chain (at least) corresponds to which HTTPRoute, and ensure that ACKs and NACKs flow backwards through the controller, so that the status of the _correct_ HTTPRoute can be updated at the right time. My experience is this is pretty hard to do right, because xDS is eventually consistent, in that even once a specific update has been ACKed, Envoy will need a (small) amount of time to flip things over. Will this be long enough to notice? Probably not, but we have no way of _guaranteeing_ it, because of the way the Kubernetes eventual consistency lines up with the Envoy xDS consistency checks.

**Comment by howardjohn** [comment]
I feel like all of those concerns apply to "Ready" at Gateway level though? Which is why we aren't implementing it today - its a Hard Problem. I'd be really interested to see if anyone with an Envoy based implementation is able to do it correctly (and handling NxM data plane/control plane replicas)

From the user perspective, what value does Ready provide (over Programmed) if it doesn' include Routes? A gateway without routes is ~useless

**Comment by arkodg** [comment]
for the `platform admin` persona
* a `Gateway` listener `Ready` status will be useful so they can be sure config like `tls` is setup
correctly in the data plane
for the `app dev` persona
* they might not have access to the `Gateway` resource
* the xRoute resource is the only resource that links the Gateway to the Backend, so a `Ready` condition here will signal to the user whether its safe to send traffic or not via this route.

yes, its a really hard problem, but hoping implementations are incentivized to solve it, since its very useful for end users

**Comment by howardjohn** [comment]
IMO we should either have `Ready` for both or neither. A partial state isn't particularly useful

**Comment by arkodg** [comment]
@dprotaso @shaneutt @robscott wouldn't this some change to an existing GEP as well to add a Route Ready condition ?

**Comment by dprotaso** [comment]
@arkodg Yeah I can write something up.

I'm putting this PR on hold until the discussion https://github.com/kubernetes-sigs/gateway-api/issues/1877 is resolved

**Comment by arkodg** [comment]
thanks for driving this @dprotaso !

**Comment by robscott** [comment]
I think we can close this one out now that we've marked "Ready" as reserved for future use: https://github.com/kubernetes-sigs/gateway-api/pull/1888.
