### ISSUE TITLE
GEP: Enable egress use case for the Gateway API

### ISSUE THREAD

**Issue by vinod4linux** [kubernetes-sigs/gateway-api#1856]
Kubernetes does not have a standard way of dealing with egress traffic - i.e. traffic originating in a cluster with a destination outside the cluster. We want to create a standard way of handling this traffic using Gateway API.

Details of this use case are specified in the document below:
https://docs.google.com/document/d/13xAF_pqH2bV8x4MfXWde47esCdVwow1-nig6iy_rafA/edit?usp=sharing

**Comment by quangnguyen101** [comment]
Thank you for opening this issue @vinod4linux.

**Comment by shaneutt** [comment]
Thanks @vinod4linux! Glad to see the continued interest in the egress topic. I think the next best step would be for someone to take this on and create an initial GEP that covers the high level "what" and "why" topics, so that we can iteratively progress towards the desired implementation. It seems most likely that we can just start that GEP using the content already provided in the google doc and take some small steps to raise awareness and build alignment with the community.

/help

**Comment by shaneutt** [comment]
As per the PR it unfortunately seems we've been unable to move forward on this, largely because we don't have multiple aligned implementations coming together that need it, but also because the problem domain has felt a bit out of scope for what Gateway API itself is trying to do.

We're going to close this for now, but we're always open to the suggestions to re-open it just let us know here if you think we should, what your thoughts are, and your plan for how we move this forward.
