### ISSUE TITLE
Move mesh test app into k8s org

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#1895]
I'd rather have this image owned by k8s/gateway-api infra so we can bundle versions of it with each release of our conformance tests. Can you create an issue to track following up on that? Shorter term can we at least use a pinned version of this image so a change in this image doesn't have an immediate impact on our conformance tests?

_Originally posted by @robscott in https://github.com/kubernetes-sigs/gateway-api/pull/1878#discussion_r1154742350_

**Comment by keithmattix** [comment]
The code for the app server is here: https://github.com/istio/istio/tree/master/pkg/test/echo

**Comment by robscott** [comment]
@keithmattix I actually did intend to close this one as I was taking the text of the issue very literally:

> I'd rather have this image owned by k8s/gateway-api infra so we can bundle versions of it with each release of our conformance tests. Can you create an issue to track following up on that? Shorter term can we at least use a pinned version of this image so a change in this image doesn't have an immediate impact on our conformance tests?

So at least from my perspective, the goal was to build an image from within Gateway API and push it to a k8s owned registry. We have accomplished both of those things, despite not actually moving the code into this repo. In my opinion duplicating the code here is not really helpful, the main goal was to ensure that we control the image and can publish updates/version however it works best for us.

I know the actual title of the issue seems to suggest some more broader action, but I don't think it's required, so will close this out. If we want to consider moving code over here maybe we should discuss that in a separate issue.

/close

**Comment by keithmattix** [comment]
Ah I misunderstood the previous discussion then; thanks for the clarification!

**Comment by LiorLieberman** [comment]
Recently came across this with https://github.com/istio/istio/issues/56400. I was not familiar with this dependency. IMO worth either bringing the image/code here and/or documenting how to build a new image if we need changes (in istio repo) 

/reopen
