### ISSUE TITLE
API spec change: missing ReferenceGrant should cause a 500 returned from a related HTTPRoute

### ISSUE THREAD

**Issue by pmalek** [kubernetes-sigs/gateway-api#1902]
**What would you like to be added**:

When an `HTTPRoute` has a missing `ReferenceGrant` then the response from that route should have the status code set to 500.

**Why this is needed**:

To make API require a specific status code when the relevant `ReferenceGrant` is missing.

**Related work**:

#1853

**Comment by youngnick** [comment]
We actually left this specifically as the same error code as other cases, so that you couldn't use the different between the codes to enumerate if a service exists.

Basically, the risk is this:
- secure namespace owner Alice creates a service she doesn't want people to know about.
- other namespace owner Mallory creates a HTTPRoute with a cross-namespace backend reference that points to a service they _know_ doesn't exist
- Mallory verifies that the HTTPRoute produces a 500 error when she checks it.
- Now, Mallory can use that HTTPRoute to find the name of the Alice's service by guessing names and looking to see which results produce a 503.

Kinda sucks that we have to hurt the UX for security reasons, but here we are.

**Comment by youngnick** [comment]
I think any change to the spec will need to not be able to be used for enumeration as I outlined above, so it's probably better to talk about what change you're proposing here.

**Comment by pmalek** [comment]
Just trying to explicitly state in the spec what #1853 is trying to achieve.

Perhaps instead of 503 we should consider 500 just like it's being done in case of https://github.com/kubernetes-sigs/gateway-api/blob/04193f7e9a7ef72585d87cc56721fa2f4567cf8f/conformance/tests/httproute-partially-invalid-via-reference-grant.go#L62-L70

**Comment by youngnick** [comment]
Yes, I think that a 500 would be fine.

**Comment by pmalek** [comment]
I'm closing this since https://github.com/kubernetes-sigs/gateway-api/pull/1853 implemented the enforcement in the conformance test and https://github.com/kubernetes-sigs/gateway-api/issues/1838 already raised the issue of spec change (which ultimately wasn't necessary)
