### ISSUE TITLE
Clarify whether trailing slash is meaningful for exact path match

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#1953]
**What happened**:
The current API spec does not clearly state if a trailing slash is meaningful in an exact path match. (It does clearly state that trailing slashes are ignored for prefix matches though).
https://github.com/kubernetes-sigs/gateway-api/blob/4b0c494fd206cb297ac7e3b0894d0ac9bee50fa9/apis/v1beta1/httproute_types.go#L272-L285

**What you expected to happen**:
Clear indication of whether or not trailing slash should matter in exact path match.

**Comment by shaneutt** [comment]
There may be some guidance in https://datatracker.ietf.org/doc/html/rfc3986/

**Comment by pleshakov** [comment]
not sure about other data planes, but in NGINX in the exact match the trailing slash matters. For example, an exact match```location = /abc/ { ... } ``` requires the request URI to be `/abc/`.

**Comment by kflynn** [comment]
In 2017, when we started Emissary, I decided that the trailing slash would always be meaningful (mostly because the spec is unclear, and I thought that prefix: /foo matching /foobar/ would confuse people).

Since then, I’ve had to write a bunch of doc on it, and I’ve been repeatedly burned in testing by the way browsers append a / but curl does not. So… not a slam-dunk but on balance I’d probably vote not to consider it significant.

**Comment by sunjayBhatia** [comment]
No strong preference either way, but Ingress v1 conformance says they are significant: https://github.com/kubernetes-sigs/ingress-controller-conformance/blob/7ee2f3e2d283acb203be862cacd593c71afb1311/features/path_rules.feature#L195-L199 (if we care about consistency for users who *may* be relying on this)

**Comment by howardjohn** [comment]
+1 to significant. I would be extremely confused on any string match where I say `exact: xyz` and it doesn't match the literal `xyz`

**Comment by shaneutt** [comment]
+1 to significant, the `Ingress` precedent compels me.
