### ISSUE TITLE
Issues around RouteBindingSelector

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#197]
RouteSelector right now is just a label selector, yet it can select literally any object an implementer determines is a route. This leads to unexpected behavior from users. For example, I may create an HttpRoute with label `env=prod` and using GatewayClass=Foo. Later, I change my GatewayClass to `istio` (for a concrete example - should apply to others as well). The Istio implementation happens to consider another object, say VirtualService, as a route as well, so now all my VirtualServices with `env=prod` are automatically selected as well, changing the behavior unexpectedly (and unconfigurable!)

I do not think this behavior is expected from users; I haven't found any examples in core K8s or related softwares of a label selector operating over multiple different object kinds, not to mention arbitrary object kinds as here.

To me, it would make a lot more sense to explicitly declare the kind we are selecting. This way the user has more control and it is explicit what is going on.

----

Additionally, I find namespaceSelector a bit hard to use. For example, consider a case where I only have permissions in my namespace `foo`. I want to configure the gateway to select routes within the namespace `foo` only. However, I cannot just say `NamespaceSelector=foo`, because it is working on namespace *labels* instead. Instead, I need to find a label that is unique to the `foo` namespace. 

Note that is its not possible to enforce this, so I actually just need to hope that no one else uses the same label - anyone that has permission to put labels on a namespace can actually bind their routes to my gateway, and I have no way to prevent this. This same issue applies to AllowedRouteNamespaces

Additionally, I may not even have RBAC permissions to put labels on my namespace, in which case I have no way to simply select only routes in my namespace.

**Comment by danehans** [comment]
xref: https://github.com/kubernetes-sigs/service-apis/issues/88

**Comment by costinm** [comment]
I agree - this creates a requirement that the namespace admin has no permission on changing Namespace labels. Otherwise a malicious/compromised namespace admin would be able to take over routes from another namespace.

If RBAC prevent namespace admins from accessing Namespace - whoever has RBAC permission for Namespace will need to be involved in routing/gateway setup, which may not be ideal.

**Comment by costinm** [comment]
A better solution would be for Gateway to (also) allow selecting a namespace by name. 

In clusters where namespace admins don't have RBAC on the Namespace itself - labels can be used safely. 

In clusters where namespace admin has RBAC on namespace - the Gateway should use the namespace name(s).

**Comment by bowei** [comment]
Discussed in office hours today:

* Explore adding "kind" to the selection mechanism. Design options:
  * List vs single Kind

Pros: 
* Very specific about what kind of route is being selected.
* Few use common cases where you will want to implicitly select all route types: DNS (25 TCP/25 UDP), maybe HTTP + GRPC?

Cons:
* Maybe more verbose.

**Comment by bowei** [comment]
The second piece regarding namespace permissions is an interesting one.
There was discussion on whether this imposes too much vs explicitly naming routes.
The conclusion was that namespace admin is highly privileged and would not be available to typical user. 

see this discussion:

https://kubernetes-sigs.github.io/service-apis/security-model/

**Comment by robscott** [comment]
I've opened a couple PRs to address part of this: 
- GatewayClass: https://github.com/kubernetes-sigs/service-apis/pull/198
- Gateway: https://github.com/kubernetes-sigs/service-apis/pull/199

**Comment by robscott** [comment]
@howardjohn @costinm Do you mind splitting this issue into 3? I believe they would look something like this:

1. RouteSelectors should include a Kind to specify the type of resources being selected.
2. It should be easier to limit the scope of selectors to the local namespace (will be fixed by #198 and #199)
3. Namespace names should be used over namespace selectors.

I don't necessarily agree with 3, but it would be good to have a separate issue to discuss this further instead of getting it mixed in with the other issues described here.

**Comment by JeremyOT** [comment]
I created #225 for 1.

**Comment by robscott** [comment]
@howardjohn I think 1 is mostly solved now that route selectors include a Kind. I think the second issue may be at least helped by https://github.com/kubernetes-sigs/service-apis/pull/285. Since there's a lot going on in this issue do you mind closing this one and creating new issues for anything that hasn't already been addressed?

**Comment by hbagdi** [comment]
ping @howardjohn

**Comment by robscott** [comment]
I think this issue is sufficiently stale that we can close it. I believe 1 is mostly handled already and if not would be helped by #594. I think the [upstream work on standard namespace labels](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/2161-apiserver-default-labels) that reached alpha in 1.21 should cover 2. Feel free to reopen if I'm missed anything.

/close
