### ISSUE TITLE
Add Initial Conformance Test Framework

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#20]
We want to ensure that controllers using these APIs are conformant. Having a good conformance test suite will help establish consistency across community implementations and help developers identify any missing pieces in their implementation. This should work similarly to the existing Kubernetes conformance tests and be accessible with the same workflows.

**Comment by aojea** [comment]
is this not related https://github.com/kubernetes-sigs/ingress-controller-conformance?

**Comment by robscott** [comment]
@aojea It is related, but unfortunately it doesn't follow the pattern established by the Kubernetes conformance tests. @aledbf has some [work in progress for ingress conformance](https://github.com/aledbf/ingress-conformance) following that pattern, I'd been thinking about using that as a starting point for work here as well.

**Comment by jpeach** [comment]
The current conformance suite was proposed and accepted on the mailing list

https://groups.google.com/d/msg/kubernetes-sig-network/dAt78O-JUCo/vvOXt3-XCgAJ
kubernetes/org#1328

Conformance testing needs to test not just the v2 API, but also Ingress v1beta1 and v1. I am not sure that it should live in this repo, since it has a broader scope. I would prefer to avoid building 2 separate suites and ending up with different overlapping tests.

Probably @aledbf and @alexgervais should discuss?

**Comment by alexgervais** [comment]
When https://github.com/kubernetes-sigs/ingress-controller-conformance started, it was intended to support `v1beta1` and `v1` Ingress APIs.

It is desirable to have a single conformance test suite for `v1beta1`, `v1` Ingress and `v2` Service APIs.  We have not committed to using the sonobuoy in kubernetes-sigs/ingress-controller-conformance, but building on a common ground would make total sense. The worst possible thing would be to completely diverge on approaches here and have the 2 suites diverge so early in their inception.

@aledbf , thoughts?

**Comment by jpeach** [comment]
xref kubernetes-sigs/ingress-controller-conformance#29

**Comment by markmc** [comment]
I think this issue was resolved by #969
