### ISSUE TITLE
Conformance: HTTPRoute Filter Combinations

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#2037]
All HTTPRoute filters now have conformance tests as covered by https://github.com/kubernetes-sigs/gateway-api/issues/1103. Now we need some tests to cover combinations of them. At minimum we should aim to have all filters tested in combination with one other filter. Here's an example of what that could look like:

**Core Combinations**
* [ ] Request Header Modifier and Request Redirect

**Core and Extended Combinations**
* [ ] Request Header Modifier and URL Rewrite
* [ ] Request Redirect and Request Mirror

**Extended Combinations**
* [ ] Response Header Modifier and Request Mirror

**Comment by Treenhan** [comment]
Had an offline chat with @LiorLieberman - I am interested in taking this.

**Comment by Treenhan** [comment]
@LiorLieberman I created a PR https://github.com/kubernetes-sigs/gateway-api/pull/2101 which combines one Core Capability (i.e. `requestHeaderModifier`) with other Extended Capabilities (i.e. `requestMirror`, `responseHeaderModifier`, and `urlRewrite`).

The list of Core/Extended capabilities was based on https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRouteFilter

There is still work investigating whether it's possible to combine `requestRedirect` with other capabilities because this capability does not seem to work in any combination.
