### ISSUE TITLE
Some GEPs not discoverable in sidebar

### ISSUE THREAD

**Issue by adleong** [kubernetes-sigs/gateway-api#2112]
Some GEPs, such as [GEP-1686](https://gateway-api.sigs.k8s.io/geps/gep-1686/) for example, do not appear to be listed in the Enhancement Proposal list in the sidebar on https://gateway-api.sigs.k8s.io/geps/overview/.  Is this meant to be a complete list of GEPs or is there some other more authoritative way to discover all of the GEPs?

**Comment by robscott** [comment]
Thanks for reporting this @adleong! This is definitely not intentional. Unfortunately we're manually adding GEPs to `mkdocs.yml` and apparently we've missed some. To fix this, someone would need to update this section to include all GEPs in `site-src/geps`:

https://github.com/kubernetes-sigs/gateway-api/blob/c9540a9cf448347da67e5b8663878b9b78810955/mkdocs.yml#L77-L106

/triage accepted
/good-first-issue
/help

**Comment by levikobi** [comment]
Hi @robscott, I've added the missing GEPs. Hope its ok.
