### ISSUE TITLE
BackendObjectReference port should be compatible with named port

### ISSUE THREAD

**Issue by davinkevin** [kubernetes-sigs/gateway-api#2420]
**What would you like to be added**: BackendObjectReference port should be compatible with named port 

**Why this is needed**:

As user of the Gateway API, I'm forced to use the port number defined by the backend service. However, this port may change and I have to sync this manually and/or automate a check for it.

In Ingress API, we have a [specific API](https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/#IngressBackend), where the `backend.service.port.name` can be used to avoid a direct relationship to a port. 
This `port.name` is a useful indirection allowing to separate the `implementation` (`port.number`) from the purpose (`port.name`).

With the GatewayAPI, we don't have this concept anymore.

**Comment by davinkevin** [comment]
@shaneutt, is it possible to remove the lifecycle for it, please?

**Comment by shaneutt** [comment]
Yes, albeit nobody has stepped up to drive it forward, it's still technically in triage so we need to check on it still.

**Comment by robscott** [comment]
For the record, this was an intentional omission of the API. Supporting named ports adds more complexity for both implementers and users and generally just introduces more ways that things can break. For anyone interested in pushing this forward, you would need to show that the value of providing this option outweighed the complexity it introduces.
