### ISSUE TITLE
GEP-1762 needs clarification on long Gateway names > 63 characters

### ISSUE THREAD

**Issue by sunjayBhatia** [kubernetes-sigs/gateway-api#2592]
**What happened**:

Prior to GEP-1762, Contour's Gateway provisioner has been adding a label to resources to denote which Gateway "owns" it: `projectcontour.io/owning-gateway-name` set to the Gateway name.

While reviewing https://github.com/kubernetes-sigs/gateway-api/pull/2582 with Contour and also implementing the Gateway infrastructure labels feature, we realized that Gateway names longer than 63 characters cause failures to create resources generated with this label.

While this can be solved for Contour's implementation-specific labels with a hash or some other solution, this is not exclusive to Contour, the upstream GEP-1762 also has requirements that may cause many implementations to run into this. Also, including a conformance test that exhibits this may be problematic for some implementations.

@skriss pointed out as well that GEP-1762 makes this same type of label, including the "owning" Gateway as the value, required for implementations that generate deployment resources dynamically: https://gateway-api.sigs.k8s.io/geps/gep-1762/#automated-deployments

**What you expected to happen**:

GEP-1762 should be amended to describe what to do with the `gateway.networking.k8s.io/gateway-name` label when dealing with a Gateway with a long name.

**How to reproduce it (as minimally and precisely as possible)**:

Run the conformance test `HTTPRouteInvalidParentRefSectionNameNotMatchingPort` (on `main`) with Contour, or create a Gateway with a name longer than 63 characters and have Contour reconcile it.

**Anything else we need to know?**:

Hashing a long Gateway name and setting that as the value of may be an answer, however that means we will lose the immediate human readability of this feature.

Another solution would be to limit Gateway names to < 63 characters and longer names would not be Accepted by implementations.

**Comment by arkodg** [comment]
vote for 2. (limit gateway names to < 63)

**Comment by mlavacca** [comment]
> Hashing a long Gateway name and setting that as the value of may be an answer, however that means we will lose the immediate human readability of this feature.

I agree this is suboptimal as we will lose the immediate human readability of this feature.

> Another solution would be to limit Gateway names to < 63 characters and longer names would not be Accepted by implementations.

Limiting the name's length is quite tricky as what should we expect from implementation?
- run a webhook to reject gateways with a too-long name (burden for the implementations) or
- mark the gateway as not accepted because a too-long name (bad UX, delete the gateway and recreate it with a new name)

We could use a label selector on gateways with length < 63. Here the problem is that we should enforce uniqueness on this field among all the gateways in every namespace and I'm not sure there is some kind of validation at kubebuilder or CEL level that can enforce this.

**Comment by robscott** [comment]
Unfortunately I think it's too late to add any kind of limit here - Gateway is a GA part of the API. Even if we could, almost all Kubernetes resources follow the same default name validation, and I don't think it it would make sense to change it here.

I think many/most Kubernetes tools will use some kind of combination of truncation and hashing when dealing with long names in places they don't fit. So although it adds additional work, it's probably good that we have conformance tests that cover longer Gateway names like this.

**Comment by sunjayBhatia** [comment]
Yep, that makes a lot of sense. I guess at the moment, unless anyone disagrees, the action item here is to update the GEP (and any other places we talk about labels perhaps) to have a prescriptive way to deal with long resource (specifically Gateway) names being added as labels

**Comment by arkodg** [comment]
@robscott can we consider adding text in the API to discourage longer than 63 chars in the name ?
implementations are already using various techniques to shorten names when creating generated resources (Deployments, Service etc) but rely on the labels like `gateway.envoyproxy.io/owning-gateway-namespace` to map the generated resource to the `Gateway` resource, since the label value limit is 63, this makes it no longer possible to consistently use labels to find resources mapped to a `Gateway`

**Comment by tao12345666333** [comment]
Even without any hard restrictions on the API, we should add documentation to mention this possibility.

**Comment by robscott** [comment]
/reopen

@howardjohn can you work on this?

**Comment by sunjayBhatia** [comment]
If noone has picked this up I can take it since it looks like we got some consensus above on documentation/recommendation updates

**Comment by robscott** [comment]
Thanks @sunjayBhatia!

/assign @sunjayBhatia

**Comment by sunjayBhatia** [comment]
PR: https://github.com/kubernetes-sigs/gateway-api/pull/3070
