### ISSUE TITLE
Configure ExternalTrafficPolicy field on auto-generated Services

### ISSUE THREAD

**Issue by jorhett** [kubernetes-sigs/gateway-api#2596]
**What would you like to be added**:

It would be nice if the Services generated by the creation of a Gateway could be configured with the `externalTrafficPolicy` field from the existing [Services spec](https://godoc.org/k8s.io/api/core/v1#ServiceSpec)

**Why this is needed**:

At the moment it is required to deploy a Gateway, and then patch the Service created by it with this field as documented at https://istio.io/latest/docs/tasks/security/authorization/authz-ingress/#network

Not acting on this forces us to patch the service after every deployment--which is an anti-pattern. The Kubernetes model is to be declarative. Hack-patching imperatively after every apply is definitely not. 

kubernetes-sigs/gateway-api#196 mentions this issue as being unsatisfactory, but was closed without providing a solution for this.

Note that this was originally opened as kubernetes-sigs/gateway-api#196 and every word there remains true. It was also closed without reason and justification, with a long rant about how it was too old and you're doing more than services now -- which I don't see how this relates?  Since discussion was abruptly closed by @youngnick when he wasn't reading what was written about the need, but instead going off the ranch on some other topics I will try to address what he said there:

> Okay, your requirement is not `externalTrafficPolicy: local` then

My requirement is exactly that. I'm open to other solutions, and would use them if available and capable of meeting the need but at this time this is the only working solution. It's required to use Istio with a local LB, as shown in the documentation link.

> presumably for layer 4 connections, since it's completely possible for HTTP connections using X-Forwarded-For or similar mechanisms.

No. The original request and this request is for this field to be set on the Service automatically generated by creation of the Gateway resource.  The `X-Forwarded-For` field can be set by an attacker, and often contains garbage.  This solution is the only viable mechanism, as proved by Istio documenting it as such plus dozens of posted issues/threads/etc.

> The API is no longer called the "Services API" for a reason - because we decided to make the constructs more general than only Kubernetes Services. It's called the Gateway API now because we intended there to be implementations that don't use a Service for describing how Layer 4 traffic gets into a cluster. That's what Gateways and Listeners are for.

Um, fine for whatever purpose those things are used for?  But when I use the currently Gateway resource, it generates a Service. And there is no way to set this field on that service without either:

* a post-deployment operation to patch the generated Service
* a cluster-wide admissions controller that patches the generated Service

> trying to reopen a three year old issue that proposes a solution, not a problem, is not a productive way of engaging with the community.

#196 described a problem, @youngnick simply decided it wasn't really a problem in his mind.  If you want to say that there's a better way to do this than setting that field, then document the solution rather than rudely insist that the need has already been met, when all documentation says otherwise.

**Comment by youngnick** [comment]
While I think that perhaps the level of ad-hominem in this issue statement could be a bit lower, I'd like to thank you for opening a new issue, so that we can discuss what you're asking for _in the current context_. Perhaps in the future I would encourage you to limit the use of words like "rudely" and so on though.

For more context, in general we prefer to have new issues logged rather than re-opening old issues because it ensures that the current context is correctly handled, which is particularly relevant in this case.

I also note that the comments you're quoting from come from #451, not #196 (this took me a bit to trace the reference, sorry).

As I said above, your point is fair - having to manually patch a resource after it's generated by an implementation does suck, and it's why we introduced the `infrastructure` stanza in Gateway in [GEP-1867](https://gateway-api.sigs.k8s.io/geps/gep-1867/), and added support for labels and annotations in [GEP-1762](https://gateway-api.sigs.k8s.io/geps/gep-1762/).

However, in our upstream API review, we got a lot of pushback on having this level of config at the Gateway level, with the suggestion being that implementations should use multiple GatewayClasses that each have a `parametersRef` set that specifies the `externalTrafficPolicy` somehow.

So, a summary:
- Is this a real issue? Yes, I agree that it is. Having to patch objects after they're created is not declarative and a bad place to be.
- Do we have a place where we might put this configuration? Yes, we need to decide if this configuration meets the criteria for inclusion in the `infrastructure` stanza. (Which in itself involves defining the criteria and future shape of that stanza. Because this is a spec that we anticipate will live for a long time, we don't want to rush into something that will have us end up in an even worse place than we are now).
- Could this whole discussion have been had in a more polite and constructive manner? Absolutely.

On the last item, reading over my comments on #451, I'll own that I could perhaps have been a bit more gentle with my phrasing. But for the future, I would suggest that coming off as _making demands_ (which is absolutely how I read the responses on #451), and then writing a pretty accusatory issue description is not conducive to a constructive discussion.

**Comment by robscott** [comment]
@jorhett The way you've written this issue feels unnecessarily harsh. Please remember the [Kubernetes Code of Conduct](https://kubernetes.io/community/code-of-conduct/), specifically:

* Demonstrating empathy and kindness toward other people
* Being respectful of differing opinions, viewpoints, and experiences

I'd also mention that many of us are spending personal time to work on this project. Please understand that there is not infinite time to address every possible feature request.

Although you're correct that many implementations currently create a Service of type LB as part of their implementation of a Gateway, that is an implementation detail, it is not actually part of Gateway API. For example, some implementations don't use LB Services today, and in the future, implementations may create L4 Cloud Gateways instead of LB Services. As @youngnick has pointed out, it's more helpful to describe the kind of behavior you'd like a Gateway to have instead of how that would be implemented (ExternalTrafficPolicy=Local).

With all that said, if you want to proceed with this, please _respectfully_ open an issue that describes the features you actually want to be configurable. ExternalTrafficPolicy=Local is really two things:

1. Route traffic to nodes with a healthy endpoint (avoid double hop)
2. Preserve Source IP

It's not clear from this issue which of those features you want and why. It's most helpful for us to understand the broader use case so we can avoid getting stuck with existing constructs.
