### ISSUE TITLE
Support for MeshFrontendHostname cannot be indicated separately.

### ISSUE THREAD

**Issue by LiorLieberman** [kubernetes-sigs/gateway-api#2711]
/area conformance

**What happened**:
Looking at [mesh-frontend-hostname.go](https://github.com/kubernetes-sigs/gateway-api/blame/main/conformance/tests/mesh-frontend-hostname.go) conformance test, it looks like every implementation that claims to support Mesh and also implements HTTPRouteResponseHeaderModification extended feature have to conform with this test. 

However it does not look like it is the case. For example Istio, [skips this test](https://github.com/kubernetes-sigs/gateway-api/blob/9a663ba09604fd0bfd364d50b1c78bd87c2305b0/conformance/reports/v1.0.0/istio-istio.yaml#L31)

Is this feature part of Core Mesh features or we should introduce new supportedFeature for it. Now there is not way to indicate if an implementation supports `Mesh`, `HTTPRouteResponseHeaderModification` but DOESNT support `MeshFrontendHostname`.

/assign @howardjohn 
/cc @robscott

**Comment by howardjohn** [comment]
I am a bit confused that we cannot report "not support MeshFrontendHostname"?

Is this not reported via

```
    skippedTests:
    - MeshFrontendHostname
```

**Comment by LiorLieberman** [comment]
Since there is no supportFeature for it, you cant really indicate it in GatewayClass Status ([ref](https://github.com/kubernetes-sigs/gateway-api/issues/2162))

**Comment by robscott** [comment]
It seems like if an individual test is regularly skipped instead of just omitting a "SupportedFeature" we should add a feature for the functionality covered by that test so it can clearly be indicated by GatewayClass status. In this case, the conformance test is mesh-specific so it may not really make a meaningful difference since Meshes don't have a way to publish Supported Features via status yet. Even if it won't make a significant difference, I'd recommend just adding a supported feature for the sake of consistency with other tests.

**Comment by LiorLieberman** [comment]
> Meshes don't have a way to publish Supported Features via status yet.

To clarify, we do publish "Mesh" in supportedFeatues in Gateway class if an implementation claims it supports [AllFeatures](https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/utils/suite/features.go#L222) (it comes from SupportMesh supportedFeature)

**Comment by robscott** [comment]
This was actually fixed by https://github.com/kubernetes-sigs/gateway-api/pull/3035
