### ISSUE TITLE
Clarifying policy TargetNotFound condition responsibility

### ISSUE THREAD

**Issue by christianang** [kubernetes-sigs/gateway-api#2755]
We are working on implementing BackendTLSPolicy in Contour.

I'd like to get clarity on how the `TargetNotFound` condition reason should work as I think there is some wonky ux here.

There is this note: `Note also that implementations MUST ONLY populate ancestor status for the Ancestor resources they are responsible for.` in [GEP-713#standard-status-struct](https://gateway-api.sigs.k8s.io/geps/gep-713/#standard-status-struct). If the `targetRef` is not found, this would read to me as the implementation is not responsible for this BackendTLSPolicy and the implementation shouldn't add a condition because it is not in the Gateway->Route->Service hierarchy. Perhaps you could say if the Route has the same `backendRef` as the BackendTLSPolicy `targetRef` it is in the hierarchy, but this wouldn't help if the user made a typo in the `targetRef`. And alternatively, having the implementations add an ancestor reference to every BackendTLSPolicy that can't find the target seems bad as well since they may be unrelated to whatever Gateway implementation is reconciling.

Of course, it will be a bit of a bad experience for a user to make a mistake in their `targetRef` config and not get an updated policy status. However, I am not sure if we want gateway implementations to be responsible for this given we either update what we can and leave some policies out if we can't match them at all or we match all of them and duplicate status information for every gateway that may exist on a cluster.

cc @sunjayBhatia

**Comment by robscott** [comment]
This is a great point, thanks @christianang! It looks like PolicyStatus (https://github.com/kubernetes-sigs/gateway-api/pull/2448) was added before BackendTLSPolicy. It seems like the idea of "TargetNotFound" could at least theoretically make sense for implementation-specific policies where we knew there would always be exactly one controller implementing the policy. Unfortunately that's not really necessarily true because it's certainly possible for multiple Gateway controllers of the same implementation to be running in the same cluster, so this may only really be applicable in a small set of cases.

Unless I'm missing something, I think we may need to revert this condition and/or think of alternatives that might work better.

/cc @youngnick @candita

**Comment by youngnick** [comment]
`targetRef` not found is actually quite similar to the case of `parentRef` not found for HTTPRoute, and we have ended up in a similar spot there - if the `parentRef` doesn't point to anything, there's _no_ status updates. Sadly, the best signal we can give here is that the status doesn't get updated at all - if your status isn't updated, then the upward reference is incorrect.

So, I'd prefer to keep this behavior and reason, even though it's a bit funky.

**Comment by candita** [comment]
I hadn't seen this before, sorry.  Also see recent https://github.com/kubernetes-sigs/gateway-api/discussions/2927, @christianang
