### ISSUE TITLE
ConformanceReports: Reports should report on ingress2gateway support

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/gateway-api#2875]
**What would you like to be added**:

Our `ConformanceReports` should include a field for [ingress2gateway](https://github.com/kubernetes-sigs/ingress2gateway) support.

This is sibling to https://github.com/kubernetes-sigs/ingress2gateway/issues/103

**Why this is needed**:

As a user that wants to migrate from `Ingress` to Gateway API, I want to be able to view the implementations page and check conformance results to know which implementations support conversion.

**Comment by mlavacca** [comment]
This one is definitely interesting but I think it is not as straightforward as it may look at first glance, as the `ingress2gateway` providers may have different levels of support. For example, Kong today converts `TCPIngress` to `Gateway`  + `TCPRoute`, but does not provide the same functionality for UDPRoutes (yet). I think this new section of the profile should describe the conversions available in the provider, instead of just being a boolean value. And also, we should refer to a specific `Ingress2Gateway` version
