### ISSUE TITLE
Conformance: Report should be optional

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#2921]
**What happened**:
Running conformance tests with the new (previously experimental) test runner requires a very long list of CLI flags for populating a conformance report (implementation details for example). That means the relatively simple commands in our corresponding documentation are now invalid: https://gateway-api.sigs.k8s.io/concepts/conformance/#running-tests.

**What you expected to happen**:
The examples in the docs to be valid. (Ideally not by making the examples more complex).

**How to reproduce it (as minimally and precisely as possible)**:
Run any of the conformance test commands in our docs.

**Comment by robscott** [comment]
cc @mlavacca @shaneutt

**Comment by dprotaso** [comment]
This is fixed on my PR here - https://github.com/kubernetes-sigs/gateway-api/pull/2864

**Comment by dprotaso** [comment]
I think you still need to select a profile though

**Comment by mlavacca** [comment]
For what concerns documentation, I already have an open PR to update it: https://github.com/kubernetes-sigs/gateway-api/pull/2848. I was waiting for the suite promotion to move it forward. 

I think that we may want to allow users to define either profiles or a specific test case, instead of requiring a profile to be always set. I'll open a PR for that as #2864 does not cover that.

**Comment by mlavacca** [comment]
In the 24-4-2 meeting, we decided to remove only implementation details requirements, already addressed by @2864. Documentation for this will be added by https://github.com/kubernetes-sigs/gateway-api/pull/2848.
