### ISSUE TITLE
Create container image repository for built images

### ISSUE THREAD

**Issue by bowei** [kubernetes-sigs/gateway-api#3]
We will need a gcr.io docker image repo for the built artifacts:

https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/README.md
https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md

**Comment by aojea** [comment]
/assign
xref: https://github.com/kubernetes/k8s.io/pull/515

**Comment by thockin** [comment]
I am curious what artifacts you expect to build and publish?

**Comment by aojea** [comment]
@bowei only is missing the `cloudbuild.yaml` 

https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md#cloudbuildyaml

and defining the artifacts https://github.com/kubernetes-sigs/service-apis/issues/3#issuecomment-566315207

**Comment by bowei** [comment]
@thockin -- conformance test suite and there are some build related images would be helpful to keep a golden image to get repeat ability.

**Comment by alexgervais** [comment]
@aojea do you know if it's possible to share a gcr.io container repo between projects? We'd like to piggyback on the work done here for the ingress-conformance images
ref. https://github.com/kubernetes-sigs/ingress-controller-conformance/issues/27

**Comment by aojea** [comment]
@alexgervais do you think that is possible to use one of the kubernetes/kubernetes images used for testing?

I think that the `agnhost` image has the same functionality

https://github.com/kubernetes/kubernetes/tree/master/test/images/agnhost#netexec

and it's maintained by the project and published to a public registry 

gcr.io/kubernetes-e2e-test-images/agnhost

**Comment by jpeach** [comment]
xref conformance test suite discussion in #20

**Comment by alexgervais** [comment]
@aojea `agnhost` is a very interesting project. However, it does not fit our requirements as the `netexec` server does not allow dumping the original request in the server's response, and injecting environment variables -- allowing us to later assert upon this data set. Also, since the behaviour of `netexec` is dictated by HTTP endpoints, it would not allow us to test the routing behaviour on matched and unmatched `Exact` or `Prefix` path types as all routes would be required to re-write the original request to `/hostname` for example.

We could of course upstream the `./tools/echoserver.go` binary cmd into `agnhost` but I think keeping this binary and docker image closer to the ingress-conformance test suite would allow us to iterate faster. 

I would also wish to publish the `ingress-controller-conformance` binary as a docker image for folks who would like to run the suite as part of their CI.

**Comment by aojea** [comment]
honestly don't know how this image publishing process works,  we should ask sig-testing if it's possible to publish artifacts from different repos to one bucket, but doesn't seem a good solution because of the complexity of maintaining it in the long term.

Maybe you can ask for a new bucket to publish images in https://github.com/kubernetes-sigs/ingress-controller-conformance?

> We will need a gcr.io docker image repo for the built artifacts:
> 
> https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/README.md
> https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md

**Comment by youngnick** [comment]
So, to follow up here, there are currently two container artifacts referenced in this repo:
- `k8s.gcr.io/service-apis-mkdocs:latest`, this is used for all docs-related tasks and is currently built from scratch each build. Making this available globally would be useful.
- `controller:latest` - this is able to be created when testing the API types using the kubebuilder code. I don't think it's used anywhere yet, since the types are not functional. Obviously, it could not be made available currently because it's not namespaced.

I think the repo for the first is a guess, and is not set in stone if it needs to be pushed somewhere else. Right now, it does nothing as the result is not pushed anywhere, and there is no push functionality in `docs.mk`.

**Comment by youngnick** [comment]
/remove-lifecycle stale
/remove-lifecycle rotten

I think the only utility here is to make the builds/testing a bit faster by allowing reuse of the mkdocs container. Given the amount of time this has lain dormant, we can probably just close it out. Thoughts?

**Comment by hbagdi** [comment]
I think this issue now becomes important again with @cmluciano's work on validating webhook, which requires a container repository (#487).
@bowei @robscott Do you have any guidance on how to go about doing this?

**Comment by aojea** [comment]
The container repository was created, it is missing to configure the repo to automate the build
https://github.com/kubernetes-sigs/service-apis/issues/3#issuecomment-573576025
