### ISSUE TITLE
Hostname regex does not allow domains ending with a . [full stop]

### ISSUE THREAD

**Issue by byhemechi** [kubernetes-sigs/gateway-api#3112]
*Route.spec.hostnames fields do not allow names ending with a full stop

**What happened**:
```
The HTTPRoute "header-echo" is invalid: spec.hostnames[0]: Invalid value: "example.com.": spec.hostnames[0] in body should match '^(\*\.)?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'
```

**What you expected to happen**:
The route is accepted

**How to reproduce it (as minimally and precisely as possible)**:
Create an HTTPRoute with a hostname value of `example.com.` and attempt to apply it

**Comment by azgabur** [comment]
Why was this closed? The hostname with "full stop" is an absolute domain name described in RFC https://datatracker.ietf.org/doc/html/rfc1034#section-3.1 and I think should be supported.

**Comment by youngnick** [comment]
This was closed by the stale bot because it made no forward progress. If you want this issue solved, then I suggest asking for it to be reopened, and then pushing forward on it by suggesting a change.

In this case, because the change is loosening validation, it's not breaking, but whoever makes this change will need to validate that underlying dataplanes actually support absolute domain names, and that the distinction is actually useful (I suspect it may not be).
