### ISSUE TITLE
hack/verify-all should output the specific tests that failed

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#3282]
**What would you like to be added**:
When a test fails in `hack/verify-all.sh`, we should output the failed tests at the end of the run.

**Why this is needed**:
Debugging test logs is _very_ complicated. For example, consider this [recent failure](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_gateway-api/3212/pull-gateway-api-verify/1825633045156204544/build-log.txt) where the output looked like this:

```
[0;32mSUCCESS: hack/../hack/verify-yamllint.sh [0m
make: *** [Makefile:113: verify] Error 1
```

The actual problematic logs were:

```
level=warning msg="[config_reader] The configuration option `linters.govet.check-shadowing` is deprecated. Please enable `shadow` instead, if you are not using `enable-all`."
conformance/tests/backendtlspolicy-normative.go:22: File is not `goimports`-ed with -local sigs.k8s.io/gateway-api (goimports)
	"k8s.io/apimachinery/pkg/types"
[0;31mTest FAILED: hack/../hack/verify-golint.sh [0m
```

It would be great to at least show the specific script that failed closer to the final output so it's more clear why `make verify` failed.

**Comment by jgao1025** [comment]
The raw file is difficult to read. 

Prew has a feature that it can only list the colored line in a build.log. Something like this - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_gateway-api/3212/pull-gateway-api-verify/1825622946182336512.

I can easily locate all errors from there, and only the problem is it starts to list the wrong lines after I click `Analyze` button even I don't have any privilege.

**Comment by TheInvincibleRalph** [comment]
Hi @robscott, I'd love to give this a shot.
