### ISSUE TITLE
Is "Gateway API" not a terrible name for the "Gateway API"?

### ISSUE THREAD

**Issue by patricekrakow** [kubernetes-sigs/gateway-api#3347]
**What would you like to be ~~added~~ replaced**:

I am probably way too late for such a suggestion, but I would love the "Gateway API" to be (re)named using another word that "Gateway". As a draft suggestion, I would propose something like "Proxy API".

**Why this is needed**:

I have discovered (quite late) that the scope of the "Gateway API" includes:
- Ingress
- Load Balancing
- and **Service Mesh**

So far, I did not look at the "Gateway API" because my area of expertise/interest is specifically around Service Mesh and not "Gateway", using the word "Gateway" (wrongly?) as a synonym of "Ingress", while using "Outbound Gateway" as a synonym of "Egress".

Now, I realized that I have been completely misguided by the word "Gateway", and I might not be the only one... It's actually to test that question that I am writing this issue.

In my (personal?) mental model what (1) a data plane proxy, used for the East-West traffic managed by a service mesh, and (2) a gateway/ingress, used for the North-South traffic, have in common to be a "proxy". The later is a proxy-on-the-edge while the first one is a proxy-as-a-sidecar[^1]. That's why having a name like "Proxy API" might have been less confusing for me, and maybe others...

However, now that I know that the Gateway API has (also) the Service Mesh configuration in scope, I will dive into it. I am pretty sure that it is almost impossible to change the name of the "Gateway API" into something else, however I wanted to check if my confusion resonates in other people minds. We all know that <https://martinfowler.com/bliki/TwoHardThings.html>, while "cache invalidation is not that hard" 😂

[^1]: sidecar should be understood here as something glued to the workload, the gluing mechanism being having containers in the same pod or the linking of a static library.

**Comment by youngnick** [comment]
@patricekrakow, you're right that it's too late to change this now.

It may help to understand that when we chose the name "Gateway", Service Mesh was _not_ in scope. It moved into scope after, when we all realized that most config that service mesh users needed was already in HTTPRoute at that point, or could be added there later.

The "Gateway" name was chosen to reflect the fact that, for ingress and load balancing use cases, there is a _translation_ between "outside", or places that don't know about cluster internals, and "inside", or places that do. The translation is a _very_ important part of why Gateway is used, because you're going from outside to inside.

I agree that most implementations of Gateway use cases use a proxy, but it's not _required_, which is why we didn't call it Proxy when we originally named it.

I think that answers this question, so I'm going to close this one, please feel free to comment if you would like it reopened.

**Comment by patricekrakow** [comment]
Thanks for sharing this historical (insightful) hint: _"[...] when we chose the name "Gateway", Service Mesh was **not** in scope."_ I still hope that, one day, you could choose another name that conveys in a better way that Service Mesh are now in scope ;-)
