### ISSUE TITLE
Assess Whether Clientgen is Required

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/gateway-api#361]
According to the kubebuilder migration [guide](https://book.kubebuilder.io/migration/guide.html), `genclient` is no longer needed in object roots. See [this](https://github.com/kubernetes-sigs/service-apis/pull/336#discussion_r496850613) for add'l background.

**Comment by robscott** [comment]
I'm not sure if I'm correctly understanding the original issue here @danehans. Is this asking if we should stop generating a client altogether or if we can safely remove the `+clientgen` tags and still continue to generate a client? I think it's valuable to provide a generated client here. Although dynamic client certainly works, it's not an ideal experience and could have scalability implications. Since the intent is for this API to be widely used, I think it makes sense to provide the best possible experience for developers using it. I'm not actually sure what combination of tags are required to continue generating that client though.

**Comment by hbagdi** [comment]
I went ahead and tested this theory out.
While `kubebuilder` doesn't need `+genclient`, `k8s.io/code-generator/cmd/client-gen` uses those tags to determine if it should create generated client for any type.

If a day comes where we want to remove the generated client from this repo, then we can remove the `+genclient` tags.

@danehans Can we close this issue out now?

**Comment by robscott** [comment]
Looks like we can close this one out, feel free to reopen if needed.

/close
