### ISSUE TITLE
Improve NamedAddressType Documentation

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/gateway-api#443]
Provide better documentation for defining what a `NamedAddressType` is. Should a `NamedAddressType` continue to be supported as "Implementation-specific" or should it be a different support level? Provide an example of a `NamedAddressType`.

**Comment by danehans** [comment]
This issue surfaced during the review of https://github.com/kubernetes-sigs/service-apis/pull/429.

**Comment by robscott** [comment]
I took a look at improving this, and I think it may already be fine. Back when this issue was opened, the description was a lot less clear (https://github.com/kubernetes-sigs/gateway-api/pull/429), but now I think we have a pretty clear example of how it can be used. Especially with my proposed addition of a hostname address type (#672), I think it's fairly clear what `NamedAddress` is intended for. I'm going to close this out, but feel free to reopen if I missed anything.

/close
