### ISSUE TITLE
Rendering of literal star characters in documentation

### ISSUE THREAD

**Issue by jberger** [kubernetes-sigs/gateway-api#539]
In reading your documentation, specifically that surrounding wildcard hostnames for a [PR on Traefik](https://github.com/traefik/traefik/issues/7874), I noticed that you appear to be suffering from markdown rendering literal `*` characters as markup generating `<em>` tags. On slack I was shown that this [had indeed been noticed](https://github.com/kubernetes-sigs/service-apis/pull/509) but the solution wasn't obvious to you. I believe if it is markdown, that wrapping the offending wildcard hostnames in backticks should be a higher precedence operation and prevent it from interpreting them as emphasis marks.

Per our discussion on slack I'm opening this bug report for tracking.

**Comment by robscott** [comment]
I did some debugging here and here's the least bad solution I could find:

```
`\*`
```

Simply using backticks without the `\` would result in the markdown appropriately getting `*` instead of `<em>`. So that solves an issue with `gen-crd-api-reference-docs`. Unfortunately we immediately turn around and try to convert that to html with mkdocs, and that predictably converts `*` to `<em>`. Adding `\` helped everything get past that step, but I think even this is probably a step too far since it makes the godocs rather confusing. Of course &ast; is also a solution that gets around this, but I think that also results in godocs that are too confusing. 

Not sure what the best path forward is here, I don't mind the switch to backticks but I can't find a great way to workaround this once we get to mkdocs. Maybe a simple sed command as part of `make docs` would work as a manual override?

/cc @jpeach

**Comment by jberger** [comment]
> Simply using backticks without the `\` would result in the markdown appropriately getting `*` instead of `<em>`. So that solves an issue with `gen-crd-api-reference-docs`. Unfortunately we immediately turn around and try to convert that to html with mkdocs, and that predictably converts `*` to `<em>`. Adding `\` helped everything get past that step, but I think even this is probably a step too far since it makes the godocs rather confusing.

I'm surprised that a doc renderer coming from html would have that problem. The backticks should render as either a pre or a code tag (can't remember which) but it should skip either

**Comment by robscott** [comment]
I think part of the problem here is that `gen-crd-api-reference-docs` is generating this:

```
<code>*</code>
```

mkdocs translates that into
```
<code><em></code>
```

On the other hand, if we manually modify the generated markdown in doc-src to this:
```
`*`
```

Running mkdocs on that results in the appropriate output:
```
`*`
```

**Comment by jberger** [comment]
I guess I'm just saying that blindly double converting from markdown seems unlikely to succeed in other cases too. Can mkdocs be taught to ignore the content of code tags?

**Comment by robscott** [comment]
Actually, yeah, that's the problem. `gen-crd-api-reference-docs` is generating HTML and we're putting it in a md file so we can include it in our generated docs easily. We probably just need a better way to include that HTML.

**Comment by jpeach** [comment]
> On 12 Feb 2021, at 10:38 am, Rob Scott <notifications@github.com> wrote:
> 
> 
> Actually, yeah, that's the problem. gen-crd-api-reference-docs is generating HTML and we're putting it in a md file so we can include it in our generated docs easily. We probably just need a better way to include that HTML.

Rename the .md to .html?
