### ISSUE TITLE
Audit the code base and make sure that our usage of custom vs implementation-specific is accurate AND/OR fix the description in the guidelines.

### ISSUE THREAD

**Issue by bowei** [kubernetes-sigs/gateway-api#640]
Audit the code base and make sure that our usage of custom vs implementation-specific is accurate AND/OR fix the description in the guidelines.

References:

* https://github.com/kubernetes-sigs/gateway-api/pull/639
* https://github.com/kubernetes-sigs/gateway-api/issues/530

**Comment by shaneutt** [comment]
This requests a quick check of all places we use custom or implementation-specific and make sure that we've documented those correctly. We ideally should have done this before `v0.5.0` (our first beta release) but since that ship has sailed, I've placed this in `v0.6.0` as something we should take care of before the next release.

**Comment by LCaparelli** [comment]
I'd like to work on this. First contrib ever, so I might need some pointers, but I'll ping on #sig-network-gateway-api if I need any help o/

@shaneutt Is there a deadline for v0.6.0 I should be mindful of?

/assign

**Comment by shaneutt** [comment]
> I'd like to work on this. First contrib ever, so I might need some pointers, but I'll ping on #sig-network-gateway-api if I need any help o/
> 
> @shaneutt Is there a deadline for v0.6.0 I should be mindful of?
> 
> /assign

Thanks @LCaparelli! We are currently targeting the week before Kubecon for the release. We appreciate you helping out with this, please let us know here in the issue or on Kubernetes slack if you need any help while working on it :vulcan_salute:
