### ISSUE TITLE
HTTPRoute matching should support custom match types

### ISSUE THREAD

**Issue by youngnick** [kubernetes-sigs/gateway-api#832]
**What would you like to be added**:

See the discussion here for more detail (https://github.com/kubernetes-sigs/gateway-api/pull/822#discussion_r696163543), but in short:

In GEP-820 (#820 and #822) we are removing the extensionRef in the HTTPRoute matches section. This issue covers work to add something back in that allows implementations to try custom matching of some sort.

@bowei suggested:
Modify `HTTPPathMatch.Type`:

* Allow qualified names (e.g. `acme.io/my-custom-match`). These represent custom match types
* The standard match types (`Exact`, `Prefix`, `RegularExpression`) stay
* Remove `ImplementationSpecific`

**Why this is needed**:
We agreed to go ahead with #822  on the proviso we come back, this is to make sure this doesn't get lost.

**Comment by hbagdi** [comment]
While I understand the motivation here, I think we should refrain from adding this. Here is why:
- Prefix, Exact, Regex, ImplementationSpecific are 4 types. That's enough of a burden we are putting on our users.
- From a product view, being clever with matches is asking for trouble. I frequently advise users to stay away from fine-grained matching semantics because mistakes are easily made and the blast radius is often larger than one can anticipate. Use another **dumber** matching criteria when possible.
- IME, asking the user to further select fine-grained differences at this level of detail doesn't go well. It becomes really hard to communicate the differences and the overall UX suffers quite a bit. At Kong, we introduced one such field and we failed. Even the maintainers have a hard time distinguishing the differences.
- Although on the surface it may feel wrong to be more opinionated and be restrictive, I think opting for simplicity and clarity is better in this case. Optimizing for esoteric cases at the cost of harming UX for 99% of the users rarely (if ever) gives any positive returns.   
- AFAIK, we do not even have use-cases for this. There should be very good reasons to justify adding this.
