### ISSUE TITLE
Add top level Gateway conditions when Routes fail to attach

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#849]
**What would you like to be added**:
Top level Gateway conditions that can be used to indicate when a Route has not been attached to any listeners within the Gateway.

**Why this is needed**:
The alternative of adding this condition to each listener is rather unwieldy. 

This idea came from a [comment thread](https://github.com/kubernetes-sigs/gateway-api/pull/839#discussion_r700722524) with @howardjohn and @youngnick.

**Comment by youngnick** [comment]
This feels like a separate Condition for sure, that could be effectively treated as a warning, basically saying "a Route tried to attach, but wasn't allowed". I can see an argument both for including (it is useful info that's not otherwise obtainable without querying the implementation somehow), and not including (it could get unwieldy/cause scale problems if there are a lot of Routes).
