### ISSUE TITLE
Route ParentRef field does not mention ReferencePolicy

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/gateway-api#973]
**What happened**:

The `Namespace` field of the `ParentRef` structure doesn't mention whether a `ReferencePolicy` is required for the controller to follow a cross-namespace reference.

**What you expected to happen**:

I would expect all cross-namespace references to check a `ReferencePolicy`.

**Comment by jpeach** [comment]
`CommonRouteSpec` says

>  For Gateways, that means the Gateway needs to allow attachment from Routes of this kind and namespace.

which I take to mean that `ReferencePolicy` is required. So this issue is just about making it clearer.

**Comment by robscott** [comment]
@jpeach I agree that this does need more clarification. My perspective here is that _something_ in the target namespace needs to explicitly allow references to a resource from resources in other namespaces for them to be considered valid. In the case of ParentRef, when it refers to Gateway, a ReferencePolicy is not relevant because the Gateway itself can configure where Routes can be attached from. On the other hand, a ReferencePolicy would be relevant when attaching to some other parent resource that did not have that kind of built in capability.

**Comment by jpeach** [comment]
@robscott I completely forgot about the `AllowedRoutes` field in the `Gateway`. While it is probably a bit unfortunate that we have two similar mechanisms, thinking about consolidation would have to be in the next API version.

**Comment by youngnick** [comment]
/remove-lifecycle stale

I think that we should say that any resource that can act as a ParentRef _must_ include something that acts like AllowedRoutes if it supports cross-namespace attachment. ReferencePolicy should be used for objects that don't have a direct Gateway API attachment formed, or that we can't change the spec of, like Secret and Service.

**Comment by youngnick** [comment]
/remove-lifecycle stale

The remaining action here is a some guidance to API designers (ie, us), that we should use a field like AllowedRoutes where we control the spec on both sides of the two-way handshake, and ReferencePolicy where we don't.

**Comment by youngnick** [comment]
/remove-lifecycle stale

I'll get this one done.

/assign
